// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WestWindLibrary.Entities;

[Index("CategoryID", Name = "CategoriesProducts")]
[Index("CategoryID", Name = "CategoryID")]
[Index("ProductName", Name = "ProductName")]
[Index("SupplierID", Name = "SupplierID")]
[Index("SupplierID", Name = "SuppliersProducts")]
public partial class Product
{
    [Key]
    public int ProductID { get; set; }

    [Display(Name = "Product Name")]
    [Required(ErrorMessage = "You must enter a {0}.")]
    [StringLength(40, ErrorMessage = "{0} must be between {2} and {1} characters.", MinimumLength = 5)]
    public string ProductName { get; set; }

    [Display(Name = "Supplier")]
    [Range(1, int.MaxValue, ErrorMessage = "You must select a {0}.")]
    public int SupplierID { get; set; }

    [Display(Name = "Category")]
    [Range(1, int.MaxValue, ErrorMessage = "You must select a {0}.")]
    public int CategoryID { get; set; }

    [Display(Name = "Quantity Per Unit")]
    [Required(ErrorMessage = "You must enter a {0}.")]
    [StringLength(20, ErrorMessage = "{0} cannot be more than {1} characters.")]
    public string QuantityPerUnit { get; set; }

    [Display(Name = "Minimum Order Quantity")]
    public short? MinimumOrderQuantity { get; set; }

    [Display(Name = "Unit Price")]
    [Required(ErrorMessage = "You must enter a {0}.")]
    [Column(TypeName = "money")]
    [Range(0.0, double.MaxValue, ErrorMessage = "{0} must be greater than {1}.")]
    public decimal UnitPrice { get; set; }

    [Display(Name = "Units On Order")]
    [Range(0, int.MaxValue, ErrorMessage = "{0} must be greater than {1}.")]
    public int UnitsOnOrder { get; set; }

    public bool Discontinued { get; set; }

    //No Data Annotation for Virtual Fields, please :)
    [ForeignKey("CategoryID")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<ManifestItem> ManifestItems { get; set; } = new List<ManifestItem>();

    [InverseProperty("Product")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [ForeignKey("SupplierID")]
    [InverseProperty("Products")]
    public virtual Supplier Supplier { get; set; }
}